# Data Cleaning 2019 Plastic Pollution Data

In [1]:
import pandas as pd

In [2]:
def drop_not_needed_columns(df: pd.DataFrame) -> pd.DataFrame:
    columns_to_drop = ['Flag Codes', 'Flags', 'TIME']

    # Check if columns exist in the DataFrame before dropping
    existing_columns = [col for col in columns_to_drop if col in df.columns]
    if existing_columns:
        df.drop(columns=existing_columns, inplace=True)

    return df

In [3]:
waste_df = pd.read_csv('../data/raw_data/plastic_waste_2019.csv')
# drop not needed columns
waste_df = drop_not_needed_columns(waste_df)
waste_df.drop(columns=(['PLASTICS_POLYMER','PLASTICS_APPLICATIONS']),inplace=True)
# apply common style
waste_df.columns = waste_df.columns.str.lower().str.replace(" ","_")
# renaming some column names
waste_df.columns = ['location_code', 'location','plastics_polymer', 'plastics_applications', 'total_waste' ]

display(waste_df.head())
waste_df.shape

,location_code,location,plastics_polymer,plastics_applications,total_waste
0,OAM,Other OECD America,Other,Other,1.024199
1,OAM,Other OECD America,"LDPE, LLDPE",Other,0.168113
2,OAM,Other OECD America,HDPE,Other,0.132488
3,OAM,Other OECD America,PS,Other,0.061802
4,OAM,Other OECD America,PVC,Other,0.209497

(1410, 5)

In [4]:
for col in waste_df.columns:
    print(col)
    print(waste_df[col].unique())

location_code
['OAM' 'O22' 'OE6' 'OPA' 'OCE' 'LAM' 'EU5' 'RAN' 'MEN' 'OAF' 'ODA' 'USA1'
 'CAN1' 'CHN1' 'IND1']
location
['Other OECD America' 'OECD EU ' 'OECD Non-EU' 'OECD Asia' 'OECD Oceania'
 'Latin America' 'Other EU' 'Other Eurasia' 'Middle East & North Africa'
 'Other Africa' 'Other non-OECD Asia' 'United States' 'Canada' 'China'
 'India']
plastics_polymer
['Other' 'LDPE, LLDPE' 'HDPE' 'PS' 'PVC' 'PUR' 'Fibres' 'Bioplastics'
 'ABS, ASA, SAN' 'PP' 'PET' 'Marine coatings' 'Road marking coatings'
 'Elastomers (tyres)' 'Total']
plastics_applications
['Other' 'Packaging' 'Consumer & institutional Products'
 'Building & construction' 'Electrical/electronics'
 'Transportation - other' 'Marine coatings' 'Industrial/machinery'
 'Personal care products' 'Textile sector - clothing'
 'Textile sector - others' 'Road marking' 'Transportation - tyres' 'Total']
total_waste
[ 1.02419888  0.16811306  0.13248803 ...  0.11757103  0.32989009
 18.51841148]

In [5]:
#create unique key
waste_df['primary_key'] = waste_df['location_code']+waste_df['plastics_polymer']+waste_df['plastics_applications']

In [6]:
#waste_df2 = waste_df.pivot_table(index=('location_code','location'),columns=['plastics_polymer','plastics_applications'], values='total_waste', aggfunc=sum)#.reset_index()
#waste_df_unstacked = waste_df2.stack().reset_index().rename_axis(None, axis=1)
#data_pivot['Location'].unique()
#waste_df_unstacked

In [7]:
waste_df.isnull().sum()

location_code            0
location                 0
plastics_polymer         0
plastics_applications    0
total_waste              0
primary_key              0
dtype: int64

In [8]:
leakage = pd.read_csv('../data/raw_data/plastic_leakage_2019.csv')
# drop not needed columns
drop_not_needed_columns(leakage)
leakage.drop(columns=(['PLASTIC_CATEGORY','PLASTIC_SOURCES']),inplace=True)
# apply common style
leakage.columns = leakage.columns.str.lower().str.replace(" ","_")
# renaming some column names
leakage.columns = ['location_code', 'location','plastic_category', 'plastic_source', 'total_leakage' ]

display(leakage.head())
leakage.shape

,location_code,location,plastic_category,plastic_source,total_leakage
0,OAM,Other OECD America,Macroplastics,Total Macroplastic,0.558108
1,OAM,Other OECD America,Macroplastics,Marine activities,0.004240
2,OAM,Other OECD America,Macroplastics,Littering,0.040186
3,OAM,Other OECD America,Macroplastics,Mismanaged,0.513682
4,OAM,Other OECD America,Microplastics,Total Microplastic,0.074018

(225, 5)

In [9]:
for col in leakage.columns:
    print(col)
    print(leakage[col].unique())

location_code
['OAM' 'O22' 'OE6' 'OPA' 'OCE' 'LAM' 'EU5' 'RAN' 'MEN' 'OAF' 'ODA' 'USA1'
 'CAN1' 'CHN1' 'IND1']
location
['Other OECD America' 'OECD EU ' 'OECD Non-EU' 'OECD Asia' 'OECD Oceania'
 'Latin America' 'Other EU' 'Other Eurasia' 'Middle East & North Africa'
 'Other Africa' 'Other non-OECD Asia' 'United States' 'Canada' 'China'
 'India']
plastic_category
['Macroplastics' 'Microplastics']
plastic_source
['Total Macroplastic' 'Marine activities' 'Littering' 'Mismanaged'
 'Total Microplastic' 'Primary pellets' 'Microbeads' 'Textile wash'
 'Tyre abrasion' 'Brake dust' 'Road markings' 'Marine coatings'
 'Artificial turf' 'Microplastics dust' 'WW sludge']
total_leakage
[5.58107760e-01 4.23992200e-03 4.01863350e-02 5.13681502e-01
 7.40176150e-02 8.63958700e-03 1.07708000e-04 1.27706000e-04
 1.73394290e-02 1.14000600e-03 1.03061500e-02 1.32969200e-03
 2.04309400e-03 1.99852170e-02 1.29990260e-02 5.50793731e-01
 1.32822210e-02 9.24726710e-02 4.45038839e-01 2.81274891e-01
 2.20357040e-02 3.36787000e-04 5.16640000e-04 7.05788100e-02
 4.77949100e-03 2.05748230e-02 5.74452900e-03 9.19303300e-03
 2.73108900e-02 1.20204183e-01 3.22853343e-01 1.11516390e-02
 3.11914000e-02 2.80510304e-01 7.53515690e-02 7.25418900e-03
 1.69809000e-04 2.06276000e-04 1.00150760e-02 6.14476000e-04
 6.83871000e-03 1.93815400e-03 3.12669100e-03 1.02806600e-02
 3.49075280e-02 9.02175610e-02 1.25147410e-02 2.45655960e-02
 5.31372240e-02 7.66067680e-02 3.91226800e-03 1.54471000e-04
 2.17493000e-04 1.47799880e-02 9.95851000e-04 6.58770900e-03
 7.04600000e-06 8.66037000e-04 6.99809400e-03 4.20878110e-02
 3.09993910e-02 3.33197400e-03 3.18676900e-03 2.44806470e-02
 1.72424840e-02 7.85499000e-04 5.81340000e-05 1.13879000e-04
 4.44489300e-03 2.93645000e-04 3.08549000e-04 1.37269000e-04
 1.81308000e-04 1.25295000e-03 9.66635700e-03 1.81672298e+00
 9.91785000e-03 7.01473210e-02 1.73665781e+00 1.76396900e-01
 1.74123430e-02 1.37635000e-04 1.57693000e-04 6.25958200e-02
 4.06025100e-03 1.95222240e-02 2.29022400e-03 3.58298800e-03
 4.79281470e-02 1.87095750e-02 6.84136130e-02 2.97582000e-04
 6.77134200e-03 6.13446890e-02 1.73423740e-02 2.07972100e-03
 5.26080000e-05 8.64330000e-05 5.44514600e-03 3.52159000e-04
 1.70021800e-03 4.39793000e-04 4.75381000e-04 3.45239300e-03
 3.25852300e-03 1.39569662e+00 5.58471100e-03 4.86142530e-02
 1.34149765e+00 1.12428089e-01 1.56303590e-02 1.63137000e-04
 2.87619000e-04 2.99636040e-02 1.88281300e-03 1.36585770e-02
 3.19390200e-03 8.88309000e-04 3.47417890e-02 1.20179810e-02
 1.40523341e+00 6.85431900e-03 5.75040540e-02 1.34087504e+00
 1.81744348e-01 1.58284520e-02 1.02000000e-07 3.04070000e-04
 5.92128470e-02 3.64648700e-03 1.55949670e-02 3.66694300e-03
 9.01136600e-03 5.02594330e-02 2.42196800e-02 3.27689578e+00
 1.76116570e-02 8.40506450e-02 3.17523348e+00 1.88301501e-01
 1.69181690e-02 2.23633000e-04 3.51330000e-05 2.80986220e-02
 1.77704500e-03 1.74783120e-02 3.57202500e-03 0.00000000e+00
 1.16494408e-01 3.70415500e-03 2.92979956e+00 4.59694690e-02
 1.19187590e-01 2.76464250e+00 3.05175843e-01 3.52743500e-02
 2.92275000e-04 3.27744000e-04 9.27490870e-02 6.53757500e-03
 1.80375480e-02 3.64862000e-03 2.14299200e-03 1.38215593e-01
 7.95005900e-03 5.60790059e-01 4.58538900e-03 1.39406781e-01
 4.16797889e-01 3.89851611e-01 3.37317010e-02 4.94283000e-04
 1.26709000e-03 9.52886220e-02 6.42052600e-03 2.73943780e-02
 1.05685320e-02 1.32086410e-02 2.98367200e-02 1.71641118e-01
 1.07156041e-01 2.10830200e-03 1.27394580e-02 9.23082800e-02
 3.28374520e-02 2.04020500e-03 6.67140000e-05 1.80443000e-04
 8.23639000e-03 5.24454000e-04 2.07681600e-03 9.58061000e-04
 1.21582600e-03 2.17537600e-03 1.53631650e-02 4.38361902e+00
 1.12143269e-01 2.39826929e-01 4.03164882e+00 4.92723266e-01
 7.42368250e-02 1.99182000e-03 4.00445900e-03 1.38897251e-01
 9.57768700e-03 4.46639750e-02 7.14227000e-03 4.14209900e-03
 1.53237034e-01 5.48298470e-02 1.94309243e+00 1.42929940e-02
 1.00623906e-01 1.82817553e+00 2.62419907e-01 2.33772560e-02
 3.75830000e-04 4.91933000e-04 5.36654750e-02 3.58108900e-03
 1.57105410e-02 3.66577200e-03 2.07865500e-03 1.27917311e-01
 3.15560460e-02]

In [10]:
use = pd.read_csv('../data/raw_data/plastic_use_2019.csv')

# drop not needed columns
drop_not_needed_columns(use)
use.drop(columns=(['PLASTICS_POLYMER','PLASTICS_APPLICATIONS']),inplace=True)
# apply common style
use.columns = use.columns.str.lower().str.replace(" ","_")
# renaming some column names
use.columns = ['location_code', 'location','plastics_applications', 'plastics_polymer', 'total_use' ]

display(use.head())
use.shape

,location_code,location,plastics_applications,plastics_polymer,total_use
0,OAM,Other OECD America,Other,Other,1.065140
1,OAM,Other OECD America,Other,"LDPE, LLDPE",0.179820
2,OAM,Other OECD America,Other,HDPE,0.132932
3,OAM,Other OECD America,Other,PS,0.062225
4,OAM,Other OECD America,Other,PVC,0.208997

(1398, 5)

In [11]:
for col in use.columns:
    print(col)
    print(use[col].unique())

location_code
['OAM' 'O22' 'OE6' 'OPA' 'OCE' 'LAM' 'EU5' 'RAN' 'MEN' 'OAF' 'ODA' 'USA1'
 'CAN1' 'CHN1' 'IND1']
location
['Other OECD America' 'OECD EU ' 'OECD Non-EU' 'OECD Asia' 'OECD Oceania'
 'Latin America' 'Other EU' 'Other Eurasia' 'Middle East & North Africa'
 'Other Africa' 'Other non-OECD Asia' 'United States' 'Canada' 'China'
 'India']
plastics_applications
['Other' 'Packaging' 'Consumer & institutional Products'
 'Building & construction' 'Electrical/electronics'
 'Transportation - other' 'Marine coatings' 'Industrial/machinery'
 'Personal care products' 'Textile sector - clothing'
 'Textile sector - others' 'Road marking' 'Transportation - tyres' 'Total']
plastics_polymer
['Other' 'LDPE, LLDPE' 'HDPE' 'PS' 'PVC' 'PUR' 'Fibres' 'Bioplastics'
 'ABS, ASA, SAN' 'Total' 'PP' 'PET' 'Marine coatings'
 'Road marking coatings' 'Elastomers (tyres)']
total_use
[ 1.06514   0.17982   0.132932 ...  0.151305  0.55751  29.333368]

In [12]:
#create unique key
use['primary_key'] = use['location_code']+use['plastics_polymer']+use['plastics_applications']

In [13]:
use

,location_code,location,plastics_applications,plastics_polymer,total_use,primary_key
0,OAM,Other OECD America,Other,Other,1.065140,OAMOtherOther
1,OAM,Other OECD America,Other,"LDPE, LLDPE",0.179820,"OAMLDPE, LLDPEOther"
2,OAM,Other OECD America,Other,HDPE,0.132932,OAMHDPEOther
3,OAM,Other OECD America,Other,PS,0.062225,OAMPSOther
4,OAM,Other OECD America,Other,PVC,0.208997,OAMPVCOther
...,...,...,...,...,...,...
1393,IND1,India,Total,Road marking coatings,0.045302,IND1Road marking coatingsTotal
1394,IND1,India,Total,Elastomers (tyres),0.553813,IND1Elastomers (tyres)Total
1395,IND1,India,Total,Bioplastics,0.151305,IND1BioplasticsTotal
1396,IND1,India,Total,"ABS, ASA, SAN",0.557510,"IND1ABS, ASA, SANTotal"
1397,IND1,India,Total,Total,29.333368,IND1TotalTotal

In [57]:
# merge waste and use df
plastic_df = pd.merge(waste_df, use, on='primary_key', how='left')

In [58]:
plastic_df

,location_code,location,plastics_polymer,plastics_applications,total_waste,primary_key,total_use
0,OAM,Other OECD America,Other,Other,1.024199,OAMOtherOther,1.065140
1,OAM,Other OECD America,"LDPE, LLDPE",Other,0.168113,"OAMLDPE, LLDPEOther",0.179820
2,OAM,Other OECD America,HDPE,Other,0.132488,OAMHDPEOther,0.132932
3,OAM,Other OECD America,PS,Other,0.061802,OAMPSOther,0.062225
4,OAM,Other OECD America,PVC,Other,0.209497,OAMPVCOther,0.208997
...,...,...,...,...,...,...,...
1405,IND1,India,Road marking coatings,Total,0.033476,IND1Road marking coatingsTotal,0.045302
1406,IND1,India,Elastomers (tyres),Total,0.199958,IND1Elastomers (tyres)Total,0.553813
1407,IND1,India,Bioplastics,Total,0.117571,IND1BioplasticsTotal,0.151305
1408,IND1,India,"ABS, ASA, SAN",Total,0.329890,"IND1ABS, ASA, SANTotal",0.557510
1409,IND1,India,Total,Total,18.518411,IND1TotalTotal,29.333368

In [59]:
plastic_df_polym = plastic_df.pivot_table(index=('location_code','location'),columns=['plastics_polymer'], values=['total_waste'], aggfunc='sum').reset_index()
#data_pivot['Location'].unique()

In [18]:
plastic_df.columns

Index(['location_code', 'location', 'plastics_polymer',
       'plastics_applications', 'total_waste', 'primary_key', 'total_use'],
      dtype='object')

##### Checking NaN values and finding method to replace them

In [19]:
plastic_df[(plastic_df['total_use'].isna()==True)]

,location_code,location,plastics_polymer,plastics_applications,total_waste,primary_key,total_use
252,OPA,OECD Asia,Marine coatings,Marine coatings,7.045900e-05,OPAMarine coatingsMarine coatings,NaN
263,OPA,OECD Asia,Elastomers (tyres),Transportation - tyres,9.055140e-04,OPAElastomers (tyres)Transportation - tyres,NaN
587,MEN,Middle East & North Africa,HDPE,Personal care products,4.530000e-07,MENHDPEPersonal care products,NaN
588,MEN,Middle East & North Africa,PP,Personal care products,1.200000e-08,MENPPPersonal care products,NaN
659,OAF,Other Africa,Elastomers (tyres),Transportation - tyres,9.974000e-05,OAFElastomers (tyres)Transportation - tyres,NaN

In [20]:
plastic_df[['total_use']].describe()

        total_use
count  985.000000
mean     0.466747
std      0.998876
min      0.000003
25%      0.024576
50%      0.122982
75%      0.412638
max      7.662625

In [21]:
#we can either leave the the NaNs as 0 or replace it with the finding out the ratio of incinerated in other africa in 2019 to total waste and use this ratio to replace nans
#we need to update then as well the total rows

In [22]:
plastic_df.columns

Index(['location_code', 'location', 'plastics_polymer',
       'plastics_applications', 'total_waste', 'primary_key', 'total_use'],
      dtype='object')

In [23]:
# finally, reorder column oder
plastic_df = plastic_df.reindex(columns=['primary_key','location_code', 'location', 'plastics_polymer',
       'plastics_applications', 'total_waste', 'total_use'])

In [24]:
plastic_df.head(2)

,primary_key,location_code,location,plastics_polymer,plastics_applications,total_waste,total_use
0,OAMOtherOther,OAM,Other OECD America,Other,Other,1.024199,1.06514
1,"OAMLDPE, LLDPEOther",OAM,Other OECD America,"LDPE, LLDPE",Other,0.168113,0.17982

In [25]:
import os  
os.makedirs('../data/cleaned_data', exist_ok=True)  
plastic_df.to_csv('../data/cleaned_data/cleaned_data_2019.csv')